version: "3.3"

services:
  nginx:
    image: bertoost/nginx:symfony
    restart: always
    volumes:
      - ".:/var/www/html:rw"
    ports:
      - "12345:80"
    networks:
      - default

  php:
    image: bertoost/php71:fpm-development
    restart: always
    extra_hosts:
      XDEBUG_HOST: ${DEV_HOST_IP}
    environment:
      BINARY_DIRECTORY: 'bin/'
      DB_HOST: 'mysql'
      DB_NAME: 'assets'
      DB_USER: 'root'
    links:
      - mysql:mysql
    secrets:
      - DB_PASS
    volumes:
      - './:/var/www/html:rw'
    networks:
      - default

  mysql:
    image: mariadb:10.3.3
    restart: always
    ports:
      - 43306:3306
    networks:
      - default
    environment:
      MYSQL_DATABASE: 'assets'
      MYSQL_ROOT_PASSWORD: 'password'

secrets:
  DB_PASS:
    file: 'secrets/db_pass'